server:
  port: 8088
spring:
  application:
    name: salesHelper
  security:
    enabled: false


  datasource:
    url: ${DB_URL}
    username: a2y
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect