server:
  port: 8080
spring:
  application:
    name: salesHelper
  security:
    enabled: false

  developer:
    token: ${DEVELOPER_TOKEN}
    secret: ${DEVELOPER_SECRET}
    enabled: true

  mail:
    host: smtp-relay.brevo.com
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}

  datasource:
    url: ${DB_URL}
    username: a2y
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expirationMillis: ${JWT_EXPIRATION_MS}